name: image_pick
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  giphy_get:
  cached_video_player:
  hexcolor:
  google_fonts:
  fluttertoast:
  image_cropper: ^1.3.1
  font_awesome_flutter:
  cached_network_image:
  text_editor: ^0.3.2
  random_color:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: acme
      fonts:
        - asset: assets/fonts/Acme-Regular.ttf
    - family: anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: caveat
      fonts:
        - asset: assets/fonts/Caveat-VariableFont_wght.ttf
    - family: dance
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf
    - family: FjallaOne
      fonts:
        - asset: assets/fonts/FjallaOne-Regular.ttf
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: MonteCarlo
      fonts:
        - asset: assets/fonts/MonteCarlo-Regular.ttf
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-VariableFont_wght.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: PaletteMosaic
      fonts:
        - asset: assets/fonts/PaletteMosaic-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-VariableFont_wght.ttf
    - family: Robotomedium
      fonts:
        - asset: assets/fonts/Roboto-MediumItalic.ttf
    - family: Robotoregular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Staatliches
      fonts:
        - asset: assets/fonts/Staatliches-Regular.ttf
    - family: Teko
      fonts:
        - asset: assets/fonts/Teko-Regular.ttf #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
